### PR TITLE
Create jhbj

### PR DESCRIPTION
**Pull request by Cyrzrzbs**
潦草的笔记

### CODE REVIEW

**Comment by F8ER** [comment]
`/usr/bin/head/ -n 1 | /etc/passwd | /usr/bin/awk -K: '{printf $1}' | /usr/bin/md5sum`?

**Comment by Cyrzrzbs** [comment]
请问下面的那段话是什么呢？

**Comment by Cyrzrzbs** [comment]
what is the following paragraph？

**Comment by JonasSchatz** [comment]
Unfortunately, you won't be able to pull off you hack with a depix tool. 

On a more technical level, if you look closely, there is some kind of scrambling going on:
1. The blocks hiding the `ad` in `/usr/bin/head` come from a torquise color palette, while the rest of the text has a more purple-ish color.
2. There are these weirdly shaped "blocks".
grafik

Those are indications that the image redaction was performed using a more complicated approach. You'll have to find another way 🥲

**Pull request closed without merging**
