### PR TITLE
Update Readme file 📝, Add Dockerfile 🚀, Update requiremnets.txt 🚨

### PR DESCRIPTION
**Pull request by alivx**

### CODE REVIEW

**Review by Saibamen — APPROVED** [review]
LGTM

**Comment by Saibamen** [comment]
Ahh and if you are touching formatting - IMO will be good to add EditorConfig: https://editorconfig.org/

**Review by cnails — APPROVED** [review]

**Review by toydotgame — CHANGES_REQUESTED** [review]
What's the point of a dockerfile in a folder where you run
```sh
python -m pip install -r requirements.txt
python depix.py -p input.png -s search.png -o output.png
```
Pip can act as the builder. There's no need here to bloat this with Docker! And in fact, your way of running docker in this is more difficult than that simple `pip` command. So, _why on Earth did you do this_?

And in `requirements.txt`, why did you have `==`? That locks it just to that version of Pillow. At least `>=` would do you well; and I won't be surprised if just about _every_ version of Pillow can run this - therefore, no need for a set version.

But, that cleaned up code looks nicer! It probably runs better too! :)

**Comment by beurtschipper** [comment]
I liked the one from toydotgame better, srry

**Pull request closed without merging**
